/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  timestamp,
  varchar,
  numeric,
  integer,
  text,
  boolean,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
import { geometryColumn } from "@payloadcms/db-postgres";
export const enum_pages_blocks_hero_section_padding_top = pgEnum(
  "enum_pages_blocks_hero_section_padding_top",
  ["none", "sm", "lg", "xl", "2xl", "3xl", "4xl"],
);
export const enum_pages_blocks_hero_section_padding_bottom = pgEnum(
  "enum_pages_blocks_hero_section_padding_bottom",
  ["none", "sm", "lg", "xl", "2xl", "3xl", "4xl"],
);
export const enum_pages_status = pgEnum("enum_pages_status", [
  "draft",
  "published",
]);
export const enum__pages_v_blocks_hero_section_padding_top = pgEnum(
  "enum__pages_v_blocks_hero_section_padding_top",
  ["none", "sm", "lg", "xl", "2xl", "3xl", "4xl"],
);
export const enum__pages_v_blocks_hero_section_padding_bottom = pgEnum(
  "enum__pages_v_blocks_hero_section_padding_bottom",
  ["none", "sm", "lg", "xl", "2xl", "3xl", "4xl"],
);
export const enum__pages_v_version_status = pgEnum(
  "enum__pages_v_version_status",
  ["draft", "published"],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
    users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
    users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
  }),
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
  },
  (columns) => ({
    media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
    media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
    media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
  }),
);

export const pages_blocks_hero = pgTable(
  "pages_blocks_hero",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    headline: varchar("headline"),
    blurb: varchar("blurb"),
    section_sectionId: varchar("section_section_id"),
    section_paddingTop: enum_pages_blocks_hero_section_padding_top(
      "section_padding_top",
    ).default("none"),
    section_paddingBottom: enum_pages_blocks_hero_section_padding_bottom(
      "section_padding_bottom",
    ).default("none"),
    primaryCta_href: varchar("primary_cta_href"),
    primaryCta_innerText: varchar("primary_cta_inner_text"),
    secondaryCta_href: varchar("secondary_cta_href"),
    secondaryCta_innerText: varchar("secondary_cta_inner_text"),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("pages_blocks_hero_order_idx").on(columns._order),
    _parentIDIdx: index("pages_blocks_hero_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("pages_blocks_hero_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_hero_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    seo_title: varchar("seo_title"),
    seo_description: varchar("seo_description"),
    seo_publishDate: timestamp("seo_publish_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    seo_siteMapPriority: numeric("seo_site_map_priority"),
    seo_geo_name: varchar("seo_geo_name"),
    seo_geo_pin: geometryColumn("seo_geo_pin"),
    seo_category: varchar("seo_category"),
    seo_robots_noindex: boolean("seo_robots_noindex"),
    seo_robots_nofollow: boolean("seo_robots_nofollow"),
    seo_robots_nocache: boolean("seo_robots_nocache"),
    seo_twitter_title: varchar("seo_twitter_title"),
    seo_twitter_description: varchar("seo_twitter_description"),
    seo_twitter_image: integer("seo_twitter_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    seo_openGraph_title: varchar("seo_open_graph_title"),
    seo_openGraph_description: varchar("seo_open_graph_description"),
    seo_openGraph_image: integer("seo_open_graph_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    seo_openGraph_alt: varchar("seo_open_graph_alt"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status("_status").default("draft"),
  },
  (columns) => ({
    pages_slug_idx: index("pages_slug_idx").on(columns.slug),
    pages_seo_twitter_seo_twitter_image_idx: index(
      "pages_seo_twitter_seo_twitter_image_idx",
    ).on(columns.seo_twitter_image),
    pages_seo_open_graph_seo_open_graph_image_idx: index(
      "pages_seo_open_graph_seo_open_graph_image_idx",
    ).on(columns.seo_openGraph_image),
    pages_updated_at_idx: index("pages_updated_at_idx").on(columns.updatedAt),
    pages_created_at_idx: index("pages_created_at_idx").on(columns.createdAt),
    pages__status_idx: index("pages__status_idx").on(columns._status),
  }),
);

export const _pages_v_blocks_hero = pgTable(
  "_pages_v_blocks_hero",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: serial("id").primaryKey(),
    headline: varchar("headline"),
    blurb: varchar("blurb"),
    section_sectionId: varchar("section_section_id"),
    section_paddingTop: enum__pages_v_blocks_hero_section_padding_top(
      "section_padding_top",
    ).default("none"),
    section_paddingBottom: enum__pages_v_blocks_hero_section_padding_bottom(
      "section_padding_bottom",
    ).default("none"),
    primaryCta_href: varchar("primary_cta_href"),
    primaryCta_innerText: varchar("primary_cta_inner_text"),
    secondaryCta_href: varchar("secondary_cta_href"),
    secondaryCta_innerText: varchar("secondary_cta_inner_text"),
    _uuid: varchar("_uuid"),
    blockName: varchar("block_name"),
  },
  (columns) => ({
    _orderIdx: index("_pages_v_blocks_hero_order_idx").on(columns._order),
    _parentIDIdx: index("_pages_v_blocks_hero_parent_id_idx").on(
      columns._parentID,
    ),
    _pathIdx: index("_pages_v_blocks_hero_path_idx").on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_blocks_hero_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const _pages_v = pgTable(
  "_pages_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_seo_title: varchar("version_seo_title"),
    version_seo_description: varchar("version_seo_description"),
    version_seo_publishDate: timestamp("version_seo_publish_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_seo_siteMapPriority: numeric("version_seo_site_map_priority"),
    version_seo_geo_name: varchar("version_seo_geo_name"),
    version_seo_geo_pin: geometryColumn("version_seo_geo_pin"),
    version_seo_category: varchar("version_seo_category"),
    version_seo_robots_noindex: boolean("version_seo_robots_noindex"),
    version_seo_robots_nofollow: boolean("version_seo_robots_nofollow"),
    version_seo_robots_nocache: boolean("version_seo_robots_nocache"),
    version_seo_twitter_title: varchar("version_seo_twitter_title"),
    version_seo_twitter_description: varchar("version_seo_twitter_description"),
    version_seo_twitter_image: integer(
      "version_seo_twitter_image_id",
    ).references(() => media.id, {
      onDelete: "set null",
    }),
    version_seo_openGraph_title: varchar("version_seo_open_graph_title"),
    version_seo_openGraph_description: varchar(
      "version_seo_open_graph_description",
    ),
    version_seo_openGraph_image: integer(
      "version_seo_open_graph_image_id",
    ).references(() => media.id, {
      onDelete: "set null",
    }),
    version_seo_openGraph_alt: varchar("version_seo_open_graph_alt"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
    autosave: boolean("autosave"),
  },
  (columns) => ({
    _pages_v_parent_idx: index("_pages_v_parent_idx").on(columns.parent),
    _pages_v_version_version_slug_idx: index(
      "_pages_v_version_version_slug_idx",
    ).on(columns.version_slug),
    _pages_v_version_seo_twitter_version_seo_twitter_image_idx: index(
      "_pages_v_version_seo_twitter_version_seo_twitter_image_idx",
    ).on(columns.version_seo_twitter_image),
    _pages_v_version_seo_open_graph_version_seo_open_graph_image_idx: index(
      "_pages_v_version_seo_open_graph_version_seo_open_graph_image_idx",
    ).on(columns.version_seo_openGraph_image),
    _pages_v_version_version_updated_at_idx: index(
      "_pages_v_version_version_updated_at_idx",
    ).on(columns.version_updatedAt),
    _pages_v_version_version_created_at_idx: index(
      "_pages_v_version_version_created_at_idx",
    ).on(columns.version_createdAt),
    _pages_v_version_version__status_idx: index(
      "_pages_v_version_version__status_idx",
    ).on(columns.version__status),
    _pages_v_created_at_idx: index("_pages_v_created_at_idx").on(
      columns.createdAt,
    ),
    _pages_v_updated_at_idx: index("_pages_v_updated_at_idx").on(
      columns.updatedAt,
    ),
    _pages_v_latest_idx: index("_pages_v_latest_idx").on(columns.latest),
    _pages_v_autosave_idx: index("_pages_v_autosave_idx").on(columns.autosave),
  }),
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index(
      "payload_locked_documents_global_slug_idx",
    ).on(columns.globalSlug),
    payload_locked_documents_updated_at_idx: index(
      "payload_locked_documents_updated_at_idx",
    ).on(columns.updatedAt),
    payload_locked_documents_created_at_idx: index(
      "payload_locked_documents_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    pagesID: integer("pages_id"),
  },
  (columns) => ({
    order: index("payload_locked_documents_rels_order_idx").on(columns.order),
    parentIdx: index("payload_locked_documents_rels_parent_idx").on(
      columns.parent,
    ),
    pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      "payload_locked_documents_rels_users_id_idx",
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      "payload_locked_documents_rels_media_id_idx",
    ).on(columns.mediaID),
    payload_locked_documents_rels_pages_id_idx: index(
      "payload_locked_documents_rels_pages_id_idx",
    ).on(columns.pagesID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    pagesIdFk: foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index("payload_preferences_key_idx").on(
      columns.key,
    ),
    payload_preferences_updated_at_idx: index(
      "payload_preferences_updated_at_idx",
    ).on(columns.updatedAt),
    payload_preferences_created_at_idx: index(
      "payload_preferences_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => ({
    order: index("payload_preferences_rels_order_idx").on(columns.order),
    parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
    pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
    payload_preferences_rels_users_id_idx: index(
      "payload_preferences_rels_users_id_idx",
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index(
      "payload_migrations_updated_at_idx",
    ).on(columns.updatedAt),
    payload_migrations_created_at_idx: index(
      "payload_migrations_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const relations_users = relations(users, () => ({}));
export const relations_media = relations(media, () => ({}));
export const relations_pages_blocks_hero = relations(
  pages_blocks_hero,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_hero._parentID],
      references: [pages.id],
      relationName: "_blocks_Hero",
    }),
  }),
);
export const relations_pages = relations(pages, ({ one, many }) => ({
  _blocks_Hero: many(pages_blocks_hero, {
    relationName: "_blocks_Hero",
  }),
  seo_twitter_image: one(media, {
    fields: [pages.seo_twitter_image],
    references: [media.id],
    relationName: "seo_twitter_image",
  }),
  seo_openGraph_image: one(media, {
    fields: [pages.seo_openGraph_image],
    references: [media.id],
    relationName: "seo_openGraph_image",
  }),
}));
export const relations__pages_v_blocks_hero = relations(
  _pages_v_blocks_hero,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_hero._parentID],
      references: [_pages_v.id],
      relationName: "_blocks_Hero",
    }),
  }),
);
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: "parent",
  }),
  _blocks_Hero: many(_pages_v_blocks_hero, {
    relationName: "_blocks_Hero",
  }),
  version_seo_twitter_image: one(media, {
    fields: [_pages_v.version_seo_twitter_image],
    references: [media.id],
    relationName: "version_seo_twitter_image",
  }),
  version_seo_openGraph_image: one(media, {
    fields: [_pages_v.version_seo_openGraph_image],
    references: [media.id],
    relationName: "version_seo_openGraph_image",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_pages_blocks_hero_section_padding_top: typeof enum_pages_blocks_hero_section_padding_top;
  enum_pages_blocks_hero_section_padding_bottom: typeof enum_pages_blocks_hero_section_padding_bottom;
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_blocks_hero_section_padding_top: typeof enum__pages_v_blocks_hero_section_padding_top;
  enum__pages_v_blocks_hero_section_padding_bottom: typeof enum__pages_v_blocks_hero_section_padding_bottom;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  users: typeof users;
  media: typeof media;
  pages_blocks_hero: typeof pages_blocks_hero;
  pages: typeof pages;
  _pages_v_blocks_hero: typeof _pages_v_blocks_hero;
  _pages_v: typeof _pages_v;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_pages_blocks_hero: typeof relations_pages_blocks_hero;
  relations_pages: typeof relations_pages;
  relations__pages_v_blocks_hero: typeof relations__pages_v_blocks_hero;
  relations__pages_v: typeof relations__pages_v;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
